dir = "."
lang = "Rust"
override_name = "schema-gen-service"
service_type = "RPCEndpoint"
spec_url = "/swagger/?format=openapi"

[services.schema-gen-service]
dev = "http://localhost:8000"

[services.MetadataService]
dev = "http://localhost:8081"
stage = "http://localhost:8081"

[urls]
dev = "http://localhost:8000"
prod = "http://localhost:8000"
stage = "http://localhost:8000"
