lang = "Rust"
dir = "."
spec_url = "/swagger/?format=openapi"
override_name = "schema-gen-service"

[services.schema-gen-service]
dev = "http://localhost:8000"

[services.MetadataService]
stage = "http://localhost:8081"
dev = "http://localhost:8081"

[urls]
prod = "http://localhost:8000"
dev = "http://localhost:8000"
stage = "http://localhost:8000"
