dir = "."
lang = "Rust"
service_type = "Executable"

[services.MetadataService]
stage = "https://api-staging.gingersociety.org/metadata"
stage_k8 = "http://metadata-service-api-service/metadata"

[services.schema-gen-service]
dev = "http://localhost:8000"
stage = "http://localhost:8000"

[portals_refs]
