version: '3'

services:
    compose:
        container_name: ginger-db-compose-service
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        environment:
            - env=prod
            - DB_NAME=django_2
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
            - ALLOWED_HOSTS=localhost
            - CSRF_TRUSTED_ORIGINS=http://localhost
        volumes:
            - ./:/app
            - ~/.gitconfig:/etc/gitconfig
            - ~/.ssh:/root/.ssh
        depends_on:
            - db
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - ./pgsql:/var/lib/postgresql/data
